name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_timezone: Europe/Amsterdam
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          commits_authoring: username
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons
          plugin_people: yes
          plugin_people_types: followers
          plugin_repositories: yes
          plugin_repositories_pinned: 6
          config_order: base.header, base.activity, base.community, repositories, languages, topics, people